### ISSUE TITLE
support libnl-tiny

### ISSUE THREAD

**Issue by rofl0r** [uoaerg/wavemon#29]
hello, i've just managed to build wavemon with [libnl-tiny](https://github.com/sabotage-linux/libnl-tiny) instead of libnl3/libnl3_genl.
what we would need to do to support it officially is basically:
(configure.ac)
```
/IF/ PKG_CHECK_MODULES([LIBNLTINY], [libnl-tiny >= 2.0] /THEN/
     [CFLAGS="$CFLAGS $LIBNLTINY_CFLAGS"],
     [LIBS="$LIBS $LIBNLTINY_LIBS"],
/ELSE/
# standard libnl3 stuff here
# libnl3 with GeNetlink support - wavemon is tracking changes to iw
PKG_CHECK_MODULES([LIBNL3], [libnl-3.0 >= 3.2], [],
                  [CFLAGS="$CFLAGS $LIBNL3_CFLAGS"],
                  [AC_MSG_ERROR(need libnl >= 3.2)])
PKG_CHECK_MODULES([LIBNL3_GENL], [libnl-genl-3.0 >= 3.2],
                  [LIBS="$LIBS $LIBNL3_GENL_LIBS"],
                  [AC_MSG_ERROR(need libnl-genl >= 3.2)])
/ENDIF/
```
i've put some invented conditionals in here, for example `/IF/`, `/ELSE/` etc, since i dont grok autoconf syntax.

**Comment by grrtrr** [comment]
Thank you for suggesting this. I thought about this and decided to not support alternative libraries, since it will later mean a lot of additional maintenance, for which I simply don't have enough time.

If there is interest, an alternative would be to record how to compile this, and then add documentation here (wiki) and/or to wavemon in case someone else is interested.

**Comment by rofl0r** [comment]
no worries, wavemon is a quite useless piece of code anyway. i had much too high expectations back when i tried it.
