### ISSUE TITLE
F1 info flashes intermittently to "no interface data" every few seconds.

### ISSUE THREAD

**Issue by Trace-2** [uoaerg/wavemon#44]
Not sure if that's a bug but seems to happen here in Debian Stretch (4.9) and also Kali 2017.3 (4.14) using the latest version available from the respective repo's (0.8.0 Jan 2 2017) ... sometimes it will stay showing "no interface data" for long periods.

This seemed to start after taking screen shots with the default screenshot app (same in both) to compare driver performance.

Have already tried uninstalling and reinstalling in both but it's still the same.

Also can you please tell me what: ESS, % chan, Radio Measure and Spectrum Mgmt mean when they show up on the F3 scan page?

Great and very helpful app when it's working ... thanks for your time.

**Comment by grrtrr** [comment]
Thanks for reporting.

Are you using network-manager or a similar utility to connect/re-connect to access points?

When 'no interface data' is shown, it means no signal/noise levels, nor signal quality was reported.
Often this means that the interface with down.

Instead of de-installing, you could double-check at those times with another tool:
- `ip link show` to see which interfaces are up/down,
- `iwconfig`  - to verify interface status using the old-style API (wireless extensions),
- `iw` - to verify interface status using the new-style API (libnl).

It is very likely that during the times you see 'no interface data', those tools would report corresponding results.

Please let me know if this works for you, so I can update the issue.

Most of the scan flags are imported from [`linux/ieee80211.h`](https://github.com/torvalds/linux/blob/master/include/linux/ieee80211.h) and seem to come from the 802.11h standard. I have not gotten around to documenting them, but would welcome input from any wireless experts, to update the wavemon documentation.

The statistics are very interesting,
- _station count / channel usage_ are only reported for [ESS](https://www.techopedia.com/definition/24968/extended-service-set-ess)
- _ESS_ only shows up if there are no station count / channel usage stats
- _Radio Measure / Spectrum Management_ are 802.11h features.

**Comment by Trace-2** [comment]
I am using Wicd in both distro's ... but I am not having to re-connect when this is happening. 

The interface does not seem to be down when "no interface data" is showing as e.g I can open a browser and surf the internet at the same time.  

**ip link show** ... shows that the interface is up when "no interface data" is showing.

**iwconfig** ... shows the same.

**iw** ... seems to just output a huge amount of help options ... is there a more specific command option that would be better?

**Comment by grrtrr** [comment]
The last tool is the most important, because it uses the same interface as wavemon.

Try one of these during the time when it flashes (maybe `watch -n.5 <cmd>`):
- `iw dev wlanX link` -- shows 'not connected when losing connection to AP'
- `iw dev wlanX station dump` -- shows AP information

where `wlanX` is the name of your wireless interface.

The _second_ think to check for are the statistics updates. The refresh on the info screen depends on `"Statistics Updates"` in the configuration screen and/or `stat_updates`  in the `wavemon.conf` file. 
If this is set too high or too low (range 10ms ... 4sec), that could be a cause.

**Comment by Trace-2** [comment]
Thought I'd found the problem ... **libncurses5-dev** wasn't installed ...  but after installing that and making sure all the other depends listed in the read me file were defo installed and up to date and a reboot it's still doing it.

- `iw dev wlan0 link` shows the same when "no interface data" and the F1 page is working properly Top command is during "no interface data" ... next command is when working properly and below that

![wlan0 link](https://user-images.githubusercontent.com/35101372/35698157-2fe503fe-0784-11e8-83ea-b648a3aa0c22.png)

- `iw dev wlanX station dump`doesn't output anything ...and it is properly installed.

![nid](https://user-images.githubusercontent.com/35101372/35698181-41051de0-0784-11e8-8972-aa2f369d2f3a.png)

The interface is definitely still connected when "no interface data" is showing.

**Comment by grrtrr** [comment]
Hi, thank you for the detailed output.

Now it all makes sense -- the kernel driver reported a crazy value for the signal strength. Are you directly near the access point?

The unit is in [dbm](https://en.wikipedia.org/wiki/DBm), which means the signal is coming into the receiver at _1 milliwatt_, which is huge signal strength for a receiver signal.

This can have 2 possible causes:
- you do have such a signal strength,
- the driver has a problem (use of uninitialized or zero value).

When the value is healthy you still have `-13dbm`, even that is a lot.

The wavemon code interprets a value of 0 as "uninitialized", at least that has been the convention over the last couple of years.
Of course, kernel drivers and their conventions change.


Can you tell me which card and driver this is (`lspci -v` as `root`)?

**Comment by Trace-2** [comment]
I can tell you exactly the driver and card as I was using wavemon to compare different driver performance.

Adapter is Alfa AWUS036ACH (1.6w) ... and the driver is a modified version of the older 4.3.20 driver ... the range is fantastic in managed mode with this driver but has decreased dramatically with the following releases which is why we were using wavemon to test different versions of the latest drivers to help track down why this has happened.

The 0dBm reading in the screenshot was just a coincidence of when I hit enter on the terminal command ... the dBm values for both instances normally hover around the -10, -15dBm mark with the odd spikes to very high signal strength ... and the terminal just happened to catch one.

A great adapter when it works properly in managed mode but when the drivers have been modded to allow monitor mode the range seems to have been badly affected and nobody is quite sure why yet ... :(

**Comment by grrtrr** [comment]
Thanks for the details. The 0dBm value was actually the give-away that there is a problem with the levels reported by the driver.

I checked the code again, when the 'no interface data' is shown, 
- 3 out of 3 possible signal fields are 0 (`signal_avg, data.signal, data.bss_signal`),
- no noise information is reported (only few cards do this).

In other words, there is nothing to show. So I am planning to either
- blank the screen if there is no usable signal data, or
- change the wording, e.g. `"No signal / noise levels reported"`.

**Comment by grrtrr** [comment]
If it is possible for you, can you (with the same driver) test the updated `master` branch?

I have decided to remove the confusing warning. Instead, it blanks the signal-level part of the screen, if no sensible data is available to display. It worked well for me in a test case, but I don't have a card that emulates similar conditions.

**Comment by grrtrr** [comment]
Thank you for your input, I have added the suggestion to the latest release, [0.8.2](https://github.com/uoaerg/wavemon/releases/tag/v0.8.2).

**Comment by Trace-2** [comment]
I'll give it a try as soon as I have some free time ... :)
