### ISSUE TITLE
libcap not configurable

### ISSUE THREAD

**Issue by neheb** [uoaerg/wavemon#54]
Currently in OpenWrt, ac_cv_lib_cap_cap_get_flag=no is set to avoid the libcap dependency. I don't know enough about autotools but I would like to request a "--without-libcap" configure parameter to avoid it as that seems to be a proper solution.

**Comment by grrtrr** [comment]
I don't understand, this seems to be more related to how OpenWrt builds.
The flag is not offered because libcap is required to build wavemon. If you try without, it will produce an error like
```bash
>gcc -O2 -Wall -pthread -I/usr/include/libnl3     wavemon.c about_scr.o conf.o conf_scr.o error.o help_scr.o info_scr.o iw_if.o iw_nl80211.o iw_scan.o lhist_scr.o llist.o scan_scr.o ui.o utils.o  -lcap -lncurses -lm  -lnl-genl-3 -lnl-3  -lnl-3  -o wavemon
error.o: In function `has_net_admin_capability':
error.c:(.text+0x146): undefined reference to `cap_get_proc'
error.c:(.text+0x15d): undefined reference to `cap_get_flag'
error.c:(.text+0x177): undefined reference to `cap_free'
collect2: error: ld returned 1 exit status
```
And it seems [OpenWrt has a libcap package](https://github.com/openwrt/packages/tree/master/libs/libcap).

Without more detail, I can not see the point of doing this.

**Comment by neheb** [comment]
That's guarded by HAVE_LIBCAP. It is not defined if not found.

**Comment by grrtrr** [comment]
Thank you, as per above commit I have added support for `configure --without-libcap`. 
If you are able to build from `master`, I'd appreciate testing; otherwise I will just close the ticket.

**Comment by neheb** [comment]
yep.
