### ISSUE TITLE
Only RX is counting up

### ISSUE THREAD

**Issue by MunchHansen** [uoaerg/wavemon#57]
Hi there,

I am working on a project with a Raspberry Pi. The wifi signal is normally pretty bad on a Raspberry Pi so I have bought a wifi range extender antenna like this one:
https://www.ebay.com/itm/600Mbps-Wireless-Internet-Signal-Booster-Wifi-Range-Extender-USB-Adapter-Antenna-/131857138867

However when I plug it into the USB the TX counter stops counting as much as without the USB extender - when monitoring the wifi with wavemon. It looks like this:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/6371955/49697407-58129580-fbb7-11e8-8bc4-6455b7ebf81e.png">

Any ideas why the USB extender stops the TX counter so much?

**Comment by grrtrr** [comment]
It seems to me that the extender is in fact just another interface, if that is the case, this could be solved by switching to the right one.

Could you provide details of your interface configuration, e.g.
- `ip link show` 
- `ifconfig`
- `iw` 

Which interface are you using by default? Is this is a Raspberry Pi 3 with on-board Wifi?

**Comment by grrtrr** [comment]
Thank you. This confirms that you have two separate network interfaces, `wlan0` and `wlan1`, both connected to the same subnet 192.168.0/24.

Both are shown as active, one receiving 117.8MiB, the other 34.7MiB; one transmitting 2.4MiB, the other 268.7 MiB. This may be the reason for seeing the tx/rx difference,
The two interfaces are competing for resources (channel bandwidth) on the same Access Point.

Both interfaces are shown as 'up', only one needs to be up in order to connect the RPI to the access point. What you could do is set one interface manually down, using
e.g.
```bash
> ip link set wlan0 down
```
To find out more about the tx counters requires finding out which one is displayed. This is found in the top left corner, as shown below:
![image](https://user-images.githubusercontent.com/5132989/49806107-164b3180-fd14-11e8-8828-9627250455e8.png)

In this example `wlan0` is used. You can change the interface via the _configuration screen_ (F7 or `p` key for _p_references), as shown below:
![image](https://user-images.githubusercontent.com/5132989/49806189-4f83a180-fd14-11e8-91e4-361be9116dae.png)

**Comment by MunchHansen** [comment]
I there again, thanks for corresponding. :-)

Would it increase my signal my setting one interface manually down?

*Med venlig hilsen/Best regards*
*Frederik Munch-Hansen*

On 11 December 2018 at 15:14:00, Gerrit Renker (notifications@github.com)
wrote:

Thank you. This confirms that you have two separate network interfaces,
wlan0 and wlan1, both connected to the same subnet 192.168.0/24.

Both are shown as active, one receiving 117.8MiB, the other 34.7MiB; one
transmitting 2.4MiB, the other 268.7 MiB. This may be the reason for seeing
the tx/rx difference,
The two interfaces are competing for resources (channel bandwidth) on the
same Access Point.

Both interfaces are shown as 'up', only one needs to be up in order to
connect the RPI to the access point. What you could do is set one interface
manually down, using
e.g.

> ip link set wlan0 down

To find out more about the tx counters requires finding out which one is
displayed. This is found in the top left corner, as shown below:
[image: image]
<https://user-images.githubusercontent.com/5132989/49806107-164b3180-fd14-11e8-8828-9627250455e8.png>

In this example wlan0 is used. You can change the interface via the
*configuration
screen* (F7 or p key for _p_references), as shown below:
[image: image]
<https://user-images.githubusercontent.com/5132989/49806189-4f83a180-fd14-11e8-91e4-361be9116dae.png>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/uoaerg/wavemon/issues/57#issuecomment-446216270>, or mute
the thread
